name: E2E Tests

on:
 pull_request:
  branches: ['main']

jobs:
 cypress-run:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2

   - name: Install dependencies
     run: yarn

   - name: Cypress run
     uses: cypress-io/github-action@v5.0.0
     with:
      build: yarn build
      start: yarn start
